# Generated by Django 4.0.6 on 2022-07-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=500, unique=True)),
                ('employee_photo', models.CharField(max_length=500, null=True)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
            ],
        ),
    ]
